MACOS_TARGET_VERSION_X86 = 10.10
MACOS_TARGET_VERSION_ARM = 11.0

TARGET_ARGS_X86 = -arch x86_64 -mmacosx-version-min=$(MACOS_TARGET_VERSION_X86)
TARGET_ARGS_ARM = -arch arm64 -mmacosx-version-min=$(MACOS_TARGET_VERSION_ARM)