#pragma once

enum EXIT_CODES {
    EXIT_CODE_SUCCESS = 0,
    EXIT_CODE_GENERAL_ERROR = 101,
    EXIT_CODE_PERMISSION_ERROR = 102,
    EXIT_CODE_WINDOW_NOT_FOUND = 103,
    EXIT_CODE_DISPLAY_NOT_FOUND = 104
};
